name: 2BitFacs 
author: "2BitRealms Dev Team" 
description: An easy to manage factions plugin for PocketMine-MP 
version: 1.0.0 
main: _2BitRealms\_2BitFacs 
api: [1.12.0] 
commands: 
  f: 
   description: 2BitFacs main command. 
   permission: 2bitfacs.f
permissions: 
 2bitfacs.f: 
   default: true 
   description: "2BitFacs main command"
