name: 2BitFacs 
author: "2BitRealms Dev Team" 
authors: ["DevBrad", "_", "_"] 
description: An easy to manage factions plugin for PocketMine-MP 
version: 1.0.0 
main: _2BitRealms\_2BitFacs 
api: [1.12.0] 
commands: 
  f: 
   description: 2BitFacs main command. 
   usage: /f help 
   permission: 2bitfacs.f 
 fop: 
   description: Allows server OP's to easily manage factions. 
   usage: /fop help 
   permission: 2bitfacs.fop 
permissions: 
 2bitfacs.f: 
   default: true 
   description: "2BitFacs main command"
 2bitfacs.fop: 
   default: op 
   description: "Allows server OP's to easily manage factions."
