#2BitFacs Plugin Main Configuration 
#Copyright (C) 2015 2-Bit Realms
#All Rights Reserved

#Do NOT Change or the plugin WILL break.
plugin-version: 0.0.1

#------------[Faction Preferences]------------#
MaxFactionNameLength: 10
MinFactionNameLength: 0
MaxPlayersPerFaction: 20

#----[Claiming Preferences]----#
ClaimingEnabled: true
ModsCanClaim: true
ModsCanUnclaim: true

#----[Chat Preferences]----#
FactionChatTag: true
FactionChatColour: GREEN

#----[Staff Preferences]----#
AdminBypassEnabled: false
