#2BitFacs Ppugin Main Configuration 
#Copyright (C) 2015 2-Bit Realms
#All Rights Reserved

#----------[Faction Preferences]----------#
MaxFactionNameLength: 10
MaxPlayersPerFaction: 20

#---[Claiming Preferences]---#
ClaimingEnabled: true
ModsCanClaim: true
ModsCanUnclaim: true

#---[Staff Preferences]---#
#Is the /f bypass command allowed?
AdminModeEnabled: false
